Portfolio-mobile-webpage
kidde60/my-portifolio pull request #2
Opened 2022-04-23 20:52 UTC by kidde60

##Portfolio mobile version
**In this project I added: **

- background images.
- placeholders.

2022-04-23 21:23 UTC, BrianSammit requested changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @kidde60 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 21:23 UTC, BrianSammit commented on portifolio.html
> +<div class="arrow">
- [ ] It would be better if you wrap all the work content into a section tag. please fix this minor issue. :+1: :smile: 

- [ ] This container of the projects has a display:grid

2022-04-23 21:23 UTC, BrianSammit commented on portifolio.html
> +<button class="button" type="button">See Project</button>
- [ ] I recommend you wrap each project into a `div` tag, 

```suggestion
<div>
<div class="placeholder">
    <img src="image/placeholder.png" alt="blank-placeholder">
</div>
<div class="another-image">
    <h3>Multi-Post Stories</h3>
        <p>
            A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.
        </p>
</div>
<div>
    <ul class="items">
        <li>css</li>
        <li>html</li>
        <li>bootstrap</li>
        <li class="ruby">Ruby</li>
    </ul>
</div>
<button class="button" type="button">See Project</button>
</div>
```

With this, you will have a more organic HTML

2022-04-24 05:03 UTC, kidde60 commented
Am now done with the changes

Sent from my iPhone

> On 24 Apr 2022, at 12:23 AM, Brian Sammit Cruz Rodriguez ***@***.***> wrote:
> 
> @BrianSammit requested changes on this pull request.
> 
> STATUS: APPROVED 🟢 👏
> 
> Hello @kidde60
> Your project is complete! There is nothing else to say other than... it's time to merge it 
> Congratulations! 🎉
> 
> TO HIGHLIGHT:
> 
> Your project is professional
> Your repo is professional
> Well structured files
> Now you can merge this branch and move on 🥇
> HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES 🤞 🍀
> 
> 
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> Please, remember to tag me in your question so I can receive the notification.
> 
> As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.
> 
> In portifolio.html:
> 
> > @@ -64,5 +64,82 @@ <h2>Software Developer</h2>
>          <li><img src="image/Icon-Medium.png" alt="M" class="media"></li>
>      </ul>
>  </div>
> +<div class="arrow">
>  It would be better if you wrap all the work content into a section tag. please fix this minor issue. 👍 😄
> 
>  This container of the projects has a display:grid
> 
> In portifolio.html:
> 
> > +<div class="placeholder">
> +    <img src="image/placeholder.png" alt="blank-placeholder">
> +</div>
> +<div class="another-image">
> +    <h3>Multi-Post Stories</h3>
> +        <p>
> +            A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.
> +        </p>
> +</div>
> +<div>
> +    <ul class="items">
> +        <li>css</li>
> +        <li>html</li>
> +        <li>bootstrap</li>
> +        <li class="ruby">Ruby</li>
> +    </ul>
> +</div>
> +<button class="button" type="button">See Project</button>
>  I recommend you wrap each project into a div tag,
> ⬇️ Suggested change
> -<div class="placeholder">
> -    <img src="image/placeholder.png" alt="blank-placeholder">
> -</div>
> -<div class="another-image">
> -    <h3>Multi-Post Stories</h3>
> -        <p>
> -            A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.
> -        </p>
> -</div>
> -<div>
> -    <ul class="items">
> -        <li>css</li>
> -        <li>html</li>
> -        <li>bootstrap</li>
> -        <li class="ruby">Ruby</li>
> -    </ul>
> -</div>
> -<button class="button" type="button">See Project</button>
> +<div>
> +<div class="placeholder">
> +    <img src="image/placeholder.png" alt="blank-placeholder">
> +</div>
> +<div class="another-image">
> +    <h3>Multi-Post Stories</h3>
> +        <p>
> +            A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.
> +        </p>
> +</div>
> +<div>
> +    <ul class="items">
> +        <li>css</li>
> +        <li>html</li>
> +        <li>bootstrap</li>
> +        <li class="ruby">Ruby</li>
> +    </ul>
> +</div>
> +<button class="button" type="button">See Project</button>
> +</div>
> With this, you will have a more organic HTML
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-04-27 08:56 UTC, closed without merging